version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
    - 27017:27017
  mysql-user:
    container_name: mysql
    image: mysql:8
    hostname: localhost
    ports:
    - 3306:3306
    environment:
    - MYSQL_DATABASE=authenticationserviceDB
    - MYSQL_ROOT_PASSWORD=Password@1
    - MYSQL_PASSWORD=Password@1
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - 15672:15672
    - 5672:5672
  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    hostname: localhost
    network_mode: host
    ports:
    - 8761:8761
    restart: always
  config-server:
    container_name: config-server
    build: ./config-server
    hostname: localhost
    network_mode: host
    depends_on:
    - eureka-server
    ports:
    - 8888:8888
    restart: always
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    hostname: localhost
    network_mode: host
    ports:
    - 8080:8080
    depends_on:
    - eureka-server
    restart: always
  authentication-service:
    container_name: authentication-service
    build: ./authentication-service
    hostname: localhost
    network_mode: host
    depends_on:
    - mysql-user
    - eureka-server
    - rabbitmq
    ports:
    - 8085:8085
    restart: always
  content-service:
    container_name: content-service
    build: ./content-service
    hostname: localhost
    network_mode: host
    ports:
    - 8086:8086
    depends_on:
    - mongodb
    - eureka-server
    restart: always
  course-service:
    container_name: course-service
    build: ./course-service
    hostname: localhost
    network_mode: host
    ports:
    - 8087:8087
    depends_on:
    - mongodb
    - eureka-server
    restart: always
  email-service:
    container_name: email-service
    build: ./email-service
    hostname: localhost
    network_mode: host
    ports:
    - 9092:9092
    depends_on:
    - eureka-server
    restart: always
  payment-service:
    container_name: payment-service
    build: ./payment-service
    hostname: localhost
    network_mode: host
    ports:
    - 8099:8099
    depends_on:
    - mongodb
    restart: always
  product-webapp:
    container_name: product-webapp
    build: ./product-webapp
    hostname: localhost
    network_mode: host
    depends_on:
    - eureka-server
    ports:
    - 4200:4200
    restart: always
  qna-service:
    container_name: qna-service
    build: ./qna-service
    hostname: localhost
    network_mode: host
    ports:
    - 9001:9001
    depends_on:
    - mongodb
    - eureka-server
    restart: always
  user-service:
    container_name: user-service
    build: ./user-service
    hostname: localhost
    network_mode: host
    ports:
    - 9000:9000
    depends_on:
    - mongodb
    - eureka-server
    restart: always