server:
  port: 8086
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: brainzo
  application:
    name: content-service
    
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka